# 256色・TrueColor対応
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# === Breach Protocol (picked) ===
set -g status-style bg='#100F16',fg='#CFEA65'
set -g status-left-length 40
set -g status-right-length 80
set -g status-left  "#[bg=#CFEA65,fg=#100F16,bold] ⏽ #S #[bg=#100F16,fg=#CFEA65] "
set -g status-right "#[fg=#35BBC4]#H #[fg=#7a8a3a]│ #[fg=#8acc4a]%H:%M #[fg=#7a8a3a]│ #[fg=#C34F4D]%Y-%m-%d "

set -g window-status-format         "#[fg=#7a8a3a] #I:#W "
set -g window-status-current-format "#[bg=#CFEA65,fg=#100F16,bold] #I:#W #[bg=#100F16,fg=#CFEA65]"

set -g message-style bg='#100F16',fg='#35BBC4'
set -g message-command-style bg='#100F16',fg='#CFEA65'

# ペイン境界線
set -g pane-border-style fg='#282E39'
set -g pane-active-border-style fg='#CFEA65'

# モード(コピーなど)
set -g mode-style bg='#CFEA65',fg='#100F16'

# マウス
set -g mouse on

set-option -g default-shell /bin/zsh
